version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  # Maintain dependencies for nuget
  - package-ecosystem: "nuget"
    directory: "src/megaphone.crawler/"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget"
    directory: "src/megaphone.crawler.tests/"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget"
    directory: "src/megaphone.crawler.core/"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget"
    directory: "src/megaphone.crawler.core.tests/"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget"
    directory: "src/megaphone.standard/"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget"
    directory: "src/megaphone.standard.tests/"
    schedule:
      interval: "daily"