name: "Megaphone Standard CI"

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
  push:
    paths:
      - 'src/megaphone.standard/**'
      - 'src/megaphone.standard.tests/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/megaphone.standard/**'
      - 'src/megaphone.standard.tests/**'
      
jobs:
   build:
    name: Megaphone Standard CI
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 3.1.x
        source-url: https://nuget.pkg.github.com/AlexandreBrisebois/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: build and test megaphone.standard
      uses: zyborg/dotnet-tests-report@v1
      with:
          project_path: "./src/megaphone.standard.tests/"
          report_name: "Megaphone Standard Tests Results"
          report_title: ${{ format('Standard CI ({0})', github.run_number) }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          gist_name: megaphone-standard-test-results.md
          gist_badge_label: 'Megaphone Standard %Counters_passed%/%Counters_total%'
          gist_token: ${{ secrets.GIST_TOKEN }}
          set_check_status_from_test_outcome: true